import streamlit as st
import pandas as pd
import os
from reconciler import reconcile, result_to_dict

st.set_page_config(
    page_title="Payment Reconciliation Dashboard",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="collapsed",
)

st.title("📊 Payment Reconciliation Dashboard")
st.markdown("January 2025 | Platform Transactions vs Bank Settlements")

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
txn_path = os.path.join(DATA_DIR, "transactions.csv")
stl_path = os.path.join(DATA_DIR, "settlements.csv")

if not os.path.exists(txn_path) or not os.path.exists(stl_path):
    st.error("Data files not found. Run `generate_data.py` first.")
    st.stop()

# Reconcile
with st.spinner("Reconciling data..."):
    result = reconcile(txn_path, stl_path)
    data = result_to_dict(result)

# Summary Cards
col1, col2, col3, col4, col5 = st.columns(5)

col1.metric("Total Transactions", data["total_transactions"])
col2.metric("Matched", data["matched"])
col3.metric("Discrepancies", len(data["discrepancies"]))
col4.metric("Total Variance", f"${abs(data['total_variance']):.2f}")
col5.metric("Rounding Drift", f"${abs(data['rounding_total']):.2f}")

st.markdown("---")

GAP_LABELS = {
    "cross_month_settlement": "Cross-Month",
    "rounding_difference": "Rounding",
    "duplicate_settlement": "Duplicate",
    "orphan_settlement": "Orphan",
    "unmatched_transaction": "Unmatched Txn"
}

# Add assumptions expander 
with st.expander("ℹ️ Assumptions", expanded=False):
    st.markdown("""
    - Each transaction has a unique ID generated by the platform
    - The bank references the platform's transaction ID when settling
    - Settlement occurs 1-2 business days after the transaction
    - All amounts are in a single currency (USD)
    - Refunds are recorded as negative amounts in the bank feed
    - Month-end cutoff is midnight UTC on January 31, 2025
    - No partial settlements - a transaction settles in full or not at all
    """)

st.subheader("Discrepancies Breakdown")

# Calculate summary counts for the filter
summary_counts = data["summary"]

# Prepare Filter Options
gap_options = ["All"]
display_options = [f"All ({len(data['discrepancies'])})"]

for gap_type, count in summary_counts.items():
    gap_options.append(gap_type)
    display_options.append(f"{GAP_LABELS.get(gap_type, gap_type)} ({count})")

# Filter Section
selected_display = st.selectbox("Filter by Gap Type", display_options)

if selected_display.startswith("All"):
    filtered_disc = data["discrepancies"]
else:
    # Find the original key
    idx = display_options.index(selected_display)
    selected_key = gap_options[idx]
    filtered_disc = [d for d in data["discrepancies"] if d["gap_type"] == selected_key]

if len(filtered_disc) == 0:
    st.info("No discrepancies found for this filter.")
else:
    # Prepare dataframe for display
    df_display = pd.DataFrame(filtered_disc)
    
    # Format and present columns nicely
    df_display["gap_type"] = df_display["gap_type"].apply(lambda x: GAP_LABELS.get(x, x))
    df_display["platform_amount"] = df_display["platform_amount"].apply(lambda x: f"${x:.2f}")
    df_display["bank_amount"] = df_display["bank_amount"].apply(lambda x: f"${abs(x):.2f}")
    df_display["variance"] = df_display["variance"].apply(lambda x: f"${x:.2f}" if x != 0 else "-")
    
    df_display = df_display[["gap_type", "transaction_id", "platform_amount", "bank_amount", "variance", "details"]]
    df_display.columns = ["Type", "Transaction ID", "Platform Amount", "Bank Amount", "Variance", "Details"]
    
    # Custom colored dataframe
    st.dataframe(df_display, use_container_width=True, hide_index=True)
